[mispfetch]
python.required = 3.13
python.version = python3.9
filename = mispfetch.py
chunked = true

[mispgetevent]
python.required = 3.13
python.version = python3.9
filename = mispgetevent.py
chunked = true

[mispgetioc]
python.required = 3.13
python.version = python3.9
filename = mispgetioc.py
chunked = true

[mispsearch]
python.required = 3.13
python.version = python3.9
filename = mispsearch.py
chunked = true

[misprest]
python.required = 3.13
python.version = python3.9
filename = misprest.py
chunked = true

[mispgetattribute]
python.required = 3.13
python.version = python3.9
filename = mispgetattribute.py
chunked = true
